# Generated by Django 5.2.4 on 2025-08-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Пройден ли KYC/верификация'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('tenant', 'Tenant'), ('landlord', 'Landlord'), ('admin', 'Admin')], default='guest', help_text='User role: tenant, landlord, admin or guest', max_length=20),
        ),
    ]
