# Generated by Django 5.2.4 on 2025-08-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_is_verified_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord'), ('admin', 'Admin')], default='tenant', help_text='User role: tenant, landlord, or admin', max_length=20),
        ),
    ]
