# Generated by Django 5.2.4 on 2025-08-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Пройден ли KYC/верификация'),
        ),
    ]
