# Generated by Django 5.2.4 on 2025-08-20 19:33

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('listings', '0003_alter_listing_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingview',
            name='viewed_on',
            field=models.DateField(db_index=True, default=datetime.date(2025, 8, 20)),
        ),
        migrations.AddConstraint(
            model_name='listingview',
            constraint=models.UniqueConstraint(fields=('user', 'listing', 'viewed_on'), name='uniq_listing_view_per_user_per_day'),
        ),
    ]
