# Generated by Django 5.2.4 on 2025-08-24 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_listingview_viewed_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingview',
            name='viewed_on',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
