# Generated by Django 5.2.4 on 2025-08-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_listingview_viewed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingview',
            name='viewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
