# Generated by Django 5.2.4 on 2025-08-08 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_title'),
        ('reviews', '0002_rename_ad_review_listing_alter_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('listing', 'tenant'), name='uniq_review_per_tenant_per_listing'),
        ),
    ]
