# Generated by Django 5.2.4 on 2025-08-11 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_status'),
        ('listings', '0003_alter_listing_title'),
        ('reviews', '0003_review_uniq_review_per_tenant_per_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='uniq_review_per_tenant_per_listing',
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='One review per booking', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='bookings.booking'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False)), fields=('tenant', 'booking'), name='one_review_per_booking'),
        ),
    ]
