# Generated by Django 5.2.4 on 2025-08-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_review_uniq_review_per_tenant_per_listing_and_more'),
    ]

    operations = [
    ]
