# Generated by Django 5.2.4 on 2025-08-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_backfill_review_booking'),
    ]

    operations = [
    ]
