# Generated by Django 5.2.4 on 2025-08-01 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(default=None, help_text='Ad being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.listing'),
            preserve_default=False,
        ),
    ]
