# Generated by Django 5.2.4 on 2025-08-08 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_listing'),
        ('listings', '0003_alter_listing_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing', 'start_date'], name='bookings_bo_listing_d217dc_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing', 'end_date'], name='bookings_bo_listing_e73481_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('listing', 'start_date', 'end_date'), name='uniq_booking_exact'),
        ),
    ]
